BEGIN;
ALTER TABLE "Doctor" ADD COLUMN IF NOT EXISTS "sourceKey" TEXT;
ALTER TABLE "Doctor" ADD COLUMN IF NOT EXISTS "sourceFiles" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Doctor" ADD COLUMN IF NOT EXISTS "reviewNotes" TEXT NOT NULL DEFAULT '';
CREATE UNIQUE INDEX IF NOT EXISTS "Doctor_sourceKey_key" ON "Doctor"("sourceKey");
ALTER TABLE "Speciality" ADD COLUMN IF NOT EXISTS "sourceKey" TEXT;
ALTER TABLE "Speciality" ADD COLUMN IF NOT EXISTS "sourceFiles" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Speciality" ADD COLUMN IF NOT EXISTS "reviewNotes" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Speciality" ADD COLUMN IF NOT EXISTS "fullDescription" TEXT NOT NULL DEFAULT '';
CREATE UNIQUE INDEX IF NOT EXISTS "Speciality_sourceKey_key" ON "Speciality"("sourceKey");
CREATE TABLE IF NOT EXISTS "ContentPage" (
 "id" SERIAL PRIMARY KEY, "sourceKey" TEXT UNIQUE, "sourceFiles" TEXT NOT NULL DEFAULT '',
 "reviewNotes" TEXT NOT NULL DEFAULT '', "title" TEXT NOT NULL, "slug" TEXT NOT NULL UNIQUE,
 "category" TEXT NOT NULL DEFAULT 'About Us', "excerpt" TEXT NOT NULL DEFAULT '',
 "body" TEXT NOT NULL DEFAULT '', "location" TEXT NOT NULL DEFAULT '', "imageUrl" TEXT NOT NULL DEFAULT '',
 "sortOrder" INTEGER NOT NULL DEFAULT 0, "published" BOOLEAN NOT NULL DEFAULT false
);
COMMIT;
